export const SHOW_LOADER = "SHOW_LOADER";
export const HIDE_LOADER = "HIDE_LOADER";

export const SHOW_TOAST = "SHOW_TOAST";
export const HIDE_TOAST = "HIDE_TOAST";

export const SHOW_CONFIRMATION = "SHOW_CONFIRMATION";
export const HIDE_CONFIRMATION = "HIDE_CONFIRMATION";

export const GET_CART_ITEMS = "GET_CART_ITEMS";
export const INCREASE_ITEM_COUNT = "INCREASE_ITEM_COUNT";
export const DECREASE_ITEM_COUNT = "DECREASE_ITEM_COUNT";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
export const CLEAR_CART = "CLEAR_CART";
export const CALCULATE_TOTALS = "CALCULATE_TOTALS";
